### ISSUE TITLE
way to build seabang with custom CC options

### ISSUE THREAD

**Issue by paulwratt** [HamAndEggs/seabang#1]
With a seabang script this is easy (ala matrixcode & pthreads examples) - (actually looking at the help text it does not look like I can pass anything except `-l` libraries, and I need `-m` cpu tuning .. )

when building the seabang binary, without hacking the Makefile, there is no way to add custom CFLAGS, CPPFLAGS or LDFLAGS at build time (passed to CC in the Makefile). Specifically I need to `-m` tune the CPU at build time.

Also being able to set some other defaults for the resulting script build (so I dont have to add them to each script - oops I cant, just libraries) would be nice (at the time I build the seabang binary) eg. SEAFLAGS.

```
CFLAGS="-march=armv7-a -mfloat-abi=hard -mfpu=neon-vfpv4"; make SEABANG="g++"  SEACPPFLAGS="" SEABANGLD=""  SEALDFLAGS="" SEAFLAGS="$CFLAGS"
```

(hmm.. actually besides the Makefile issues, the others sound like the things we were talking about on the forum)

FYI: There is a quirk on some GCC builds where a certain library hast to me included twice in the link process _and_ that second reference _must_ be the last on the line .. (cant think of which library of the top of my head) .. so some way to pre-empt that when seabang binary is built would be nice (eg via the above example).

at run time the seabang binary should still be able to access CFLAGS, CPPFLAGS or LDFLAGS as well. (where CFLAGS are the compiler flags, CPPFLAGS are the Pre-Processor flags, and LDFLAGS are the linker flags)

Those are the same flags used to set up `./configure` scripts and most `make` environments (including cmake).

**Comment by HamAndEggs** [comment]
Hi Paul. I've have set up a cmake file and made seabang code to use the same c++ compiler that cmake chooses. Seems to work ok on my system. Also the cmake file is setup so that 'make install' also works.

Something went a bit odd with github and it got me to merge the branch that I was using to make this change into the main branch. So the change is in the main branch, I would have preferred to have made that merge after you feedback. :) 

As for the lib that needs to be included twice. I have too seen this. I will investigate. If you have an example could you post is so that I can add it to the examples and fix any issues.

Thanks. :)

**Comment by paulwratt** [comment]
Thanks, it should be fine merged into main

the doulbe lib thing: I wish I could remeber the exact details. It may have been a quirk of a GCC version, or a GCC in general, it may have even been `libm` with the last. I'll see what I can do, I think I know where it was discussed, its just 2+ years ago now 
:)

I'll try test seabang some more, I'm just stretched a bit thin atm. But I did want to find the exact details for another issue too ..
